# This is a basic workflow to help you get started with Actions

name: toxicity-bot

on: [issue_comment, pull_request_review]

jobs:
  toxic_check:
    runs-on: ubuntu-latest
    name: Safe space
    steps:
      - uses: actions/checkout@v2
      - name: Safe space - action step
        uses: charliegerard/safe-space@master
        with:
          GITHUB_TOKEN: 9a69d69c57b69dd9712ed4c660e366fd857051b5
