# This is a basic workflow to help you get started with Actions

name: toxicity-bot

on: [issue_comment, pull_request_review]

jobs:
  toxic_check:
    runs-on: ubuntu-latest
    name: Safe space
    steps:
      - uses: actions/checkout@v2
      - name: Safe space - action step
        uses: charliegerard/safe-space@master
        with:
          GITHUB_TOKEN: 6097a158b2afa23e6dd07410f7f81d7f82f8b619
